#!/bin/sh

# Get author and committer details
AUTHOR_NAME=$(git log -1 --format="%an")
AUTHOR_EMAIL=$(git log -1 --format="%ae")
COMMITTER_NAME=$(git config user.name)
COMMITTER_EMAIL=$(git config user.email)

# Check for identity match
if [ "$AUTHOR_NAME" = "$COMMITTER_NAME" ] || [ "$AUTHOR_EMAIL" = "$COMMITTER_EMAIL" ]; then
  echo "Error: author information is missing."
  echo "Please, use the option --author=\"Name Surnaname <user@email.com>\" to specify your identity."
  exit 1  # Prevent the commit
fi
