cardid 10
robotPart left_hand
width 1000
height 1000
xpos 32
ypos 32

#placements are
#
#     1  2
#  0        3   
#  
#      10
# 4       8
#        9
#      11 

#             x     y     th   gain    leftright LayoutNum

[SENSORS]
fakePalm        10  -30     -30     0  4   0  0
triangle_10pad	9	-1	    -23	   -60	4   1  0
triangle_10pad	6	-17	    -32	   -120	4   1  0
triangle_10pad	7	-17	    -51	   -180	4	1  0
triangle_10pad	5	-33	    -23	   -60  4	1  0
fingertipMID    0   -58     -30     20  4   0  0
fingertipMID    1   -40     -5      10  4   0  0
fingertipMID    2   -18     -0      0   4   0  0
fingertipMID    3    4      -0      0   4   0  0
fingertipMID    4    22     -15     5   4   0  0 
