cardid 10
robotPart right_hand
width 1000
height 1000
xpos 32
ypos 32

#placements are
#
#     2  1  
#  3        0   
#  
#               4    
#       
#       
#       

#             x     y     th   gain    leftright LayoutNum

[SENSORS]
fakePalm        10  -30    -30   0    4    0   0
triangle_10pad	5	-1	   -23	 180  4	   0   0
triangle_10pad	6	-17	   -32	 120  4	   0   0
triangle_10pad	9	-17	   -51	-180  4    0   0
triangle_10pad	7	-33	   -23	 60	  4	   0   0
fingertipMID    0   -58    -30   20   4    0   0
fingertipMID    1   -40    -5    10   4    0   0
fingertipMID    2   -18    -0    0    4    0   0
fingertipMID    3    4     -0    0    4    0   0
fingertipMID    4    22    -15   5    4    0   0 
  