name: CI Workflow with nodeps CMake preset

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get install -y cmake build-essential

    - name: Configure
      run: |
        cmake --preset nodeps

    - name: Build
      run: |
        cmake --build --preset nodeps

    - name: Install
      run: |
        cd build
        cmake --install .
